name: Eleventy Publish
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Are you sure you want to run the publish process manually?'
        required: true 
        type: boolean
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.7.0
      - run: npm ci
      - run: npm run publish:prod
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_public
          cname: hotwired.dev
